use_cuda: True
GPU: [0,1,2,3,4,5]           # list of gpu ids

data_path: "D:\\paris\\"
mask_path: "D:\\IRMASK\\irregular_mask\\disocclusion_img_mask"
image_shape: [256,256,3]
mask_shape:  [256,256,1]
with_subfolder: True
random_crop: True
return_name: False
batch_size : 4
num_workers : 4
input_dim : 3
cnum : 64


VERBOSE: 1
LR: 0.0001                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
MAX_ITERS: 2e6                # maximum number of iterations to train the model

L1_LAMBDA: 10 
COARSE_L1_LOSS_WEIGHT: 1
L1_LOSS_WEIGHT: 1             # l1 loss weight
STYLE_LOSS_WEIGHT: 250        # style loss weight
CONTENT_LOSS_WEIGHT: 0.1      # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1  # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge

SAVE_INTERVAL: 1000         # how many iterations to wait before saving model (0: never)
SAMPLE_INTERVAL: 1000         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 2              # number of images to sample
EVAL_INTERVAL: 0              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 100           # how many iterations to wait before logging training status (0: never)
